<a href="https://colab.research.google.com/github/leejonghyeon99/python_stu/blob/main/01_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
panel data and analysis<br>
공식: https://pandas.pydata.org<br>
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fzy1Or%2FbtqM39h0uLB%2FfHnntePsHiwAIFStdqGsLk%2Fimg.png)

<img src="http://image.yes24.com/Goods/73268296/800x0" width="200px">


In [ ]:
# Pandas : 데이터 분석 라이브러리
# 행(row), 열(column) 형태의 정형 데이터 객체를 다룸
#  2차원 데이터
#  엑셀의 시트, RDB 의 테이블과 같은 형태

# 대표적인 객체는
# DataFrame 과 Series

In [ ]:
# 기본적으로 numpy 의 array 에서 사용한 많은 기능들이 그대로 적용됨
# shape, len(), ndim, size..
# index, slicing
# sum(), mean() 등..
# filtering 기능들
# iterable 특징
# excel 등 데이터 호환

# Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 **인덱싱 기능**이 추가된 **1차원 배열**을 나타냄 (index x value 의 형태)
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성, 지정할 경우 명시적으로 지정된 index를 사용
  - **같은 타입**의 0개 이상의 데이터를 가질 수 있음

In [ ]:
import numpy as np
import pandas as pd

# Series 생성

In [ ]:
# 데이터를 직접 주어 Series 생성

s1 = pd.Series([1, 2, 3])
s1

# index 는 기본적으로 0-base 로 생성

0    1
1    2
2    3
dtype: int64

## .values  .index   .dtype

In [ ]:
s1.values   # numpy 의 array 다!

array([1, 2, 3])

In [ ]:
s1.index   # 기본적으로 0-base 인덱스

RangeIndex(start=0, stop=3, step=1)

In [ ]:
s1.dtype

dtype('int64')

In [ ]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int64

In [ ]:
# 인덱싱
s3[4]

4

In [ ]:
# data, index 를 함께 사용하여 Series 생성

In [ ]:
# pd.Series(
#     data=None,  첫번째는 data
#     index=None,  두번째는 index
#     dtype=None,
#     name=None,
#     copy=False,
#     fastpath=False,
# )

In [ ]:
s4 = pd.Series([1, 2, 3], [100, 200, 300])
s4

100    1
200    2
300    3
dtype: int64

In [ ]:
# s4[0]  # KeyError

In [ ]:
s4[100]

1

In [ ]:
s4.index

Int64Index([100, 200, 300], dtype='int64')

In [ ]:
# index 는 굳이 정수일 필요는 없다

s5 = pd.Series([1, 2, 3], ['진무', '찐무', '찜무'])
s5

진무    1
찐무    2
찜무    3
dtype: int64

In [ ]:
s5['찜무']

3

In [ ]:
# index 는 중복 허용한다 ?!?!?
s6 = pd.Series([34, 32, 30], ['장고운', '장고운', '김효은'])
s6

장고운    34
장고운    32
김효은    30
dtype: int64

In [ ]:
# 동일한 index가 여러개 있는 경우!
s6['장고운']  # 헉! 결과가 Series 로 !

장고운    34
장고운    32
dtype: int64

In [ ]:
# dict 로 Series 만들기
sdata = {'최진무': 35000, '이종현': 67000, '송민호': 12000, '조재환': 4000}
s6 = pd.Series(sdata)
s6

최진무    35000
이종현    67000
송민호    12000
조재환     4000
dtype: int64

In [ ]:
# dtype 은 pandas 에서 유추함
pd.Series([10, 20, 3.14])  # float64 로 유추

pd.Series([10, 20, 3.14], dtype=np.float32)

0    10.00
1    20.00
2     3.14
dtype: float32

In [ ]:
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int64

In [ ]:
s3.index

RangeIndex(start=0, stop=200, step=1)

In [ ]:
s3.index.values    # s2.values 와 헷갈리지 말자.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [ ]:
arr1[[0, 1, 4]]

array([10, 20, 50])

In [ ]:
arr1[[0,0, 0, 0, 1, 1, 1, 1]]

array([10, 10, 10, 10, 20, 20, 20, 20])

In [ ]:
arr1[0], arr1[[0]]

(10, array([10]))

In [ ]:
s3[4]

4

In [ ]:
s3[[4, 6, 7, 7, 8]]

4    4
6    6
7    7
7    7
8    8
dtype: int64

In [ ]:
s6

최진무    35000
이종현    67000
송민호    12000
조재환     4000
dtype: int64

In [ ]:
s6['최진무'] = 98000  # 값 수정

In [ ]:
s6

최진무    98000
이종현    67000
송민호    12000
조재환     4000
dtype: int64

In [ ]:
s6['임승빈'] = 77000   # 기존에 없던 인덱스에 값을 대입하면 --> 새로이 생긴다!

s6

최진무    98000
이종현    67000
송민호    12000
조재환     4000
임승빈    77000
dtype: int64

In [ ]:
s6[['최진무', '이종현']]  = 100, 200  # 한번에 여러개 값 수정 가능!

s6

최진무      100
이종현      200
송민호    12000
조재환     4000
임승빈    77000
dtype: int64

### 인덱스 재사용

In [ ]:
s6

최진무      100
이종현      200
송민호    12000
조재환     4000
임승빈    77000
dtype: int64

In [ ]:
s8 = pd.Series(np.arange(5), s6.index)  # <- 기존 인덱스 재사용
s8

최진무    0
이종현    1
송민호    2
조재환    3
임승빈    4
dtype: int64

# Series 의 name, index name

In [ ]:
s6

최진무      100
이종현      200
송민호    12000
조재환     4000
임승빈    77000
dtype: int64

In [ ]:
s6.name #?

In [ ]:
s6.name = '급여'
s6

최진무      100
이종현      200
송민호    12000
조재환     4000
임승빈    77000
Name: 급여, dtype: int64

In [ ]:
# Series 의 index 에도 name 을 붙여줄수 있다
s6.index.name = '이름'
s6

이름
최진무      100
이종현      200
송민호    12000
조재환     4000
임승빈    77000
Name: 급여, dtype: int64

In [ ]:
s6.index

Index(['최진무', '이종현', '송민호', '조재환', '임승빈'], dtype='object', name='이름')

In [ ]:
# index 변경 가능
s6.index = ['철희', '창희', '주희', '권희', '지우?']

s6

철희       100
창희       200
주희     12000
권희      4000
지우?    77000
Name: 급여, dtype: int64

## **Series ndim, shape, size, len, unique, count, value_counts 함수**
 - size : 개수 반환
 - shape : 튜플형태로 shape반환
 - unique: 유일한 값만 ndarray로 반환
 - count : NaN을 제외한 개수를 반환
 - mean: NaN을 제외한 평균
 - value_counts: NaN을 제외하고 각 값들의 빈도를 반환

In [ ]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])
s1

# NaN (Not a Number : 숫자가 들어와야 하는데 숫자가 아닌 값)
# 실무 데이터를 다루다 보면 NaN 을 엄청나게 자주 만나게 된다.
#    원본데이터의 '누락' 이라든지, DBMS 상의 null 값이라든지 등등. 여러가지 이슈로 NaN 값 발생
#    그래서 데이터 분석시 NaN 값을 제거 하든지 혹은 치환 하든지.. 해서 처리할줄 알아야 한다

# 그래서 이번 예제에서 NaN 값도 넣어보도록 하겠습니다.

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [ ]:
s1.ndim

1

In [ ]:
s1.shape

(16,)

In [ ]:
s1.size

16

In [ ]:
len(s1)

16

In [ ]:
s1.count()  # 실제 데이터만 count 한다!  NaN 제외된다!

15

In [ ]:
s1.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

### numpy 와 Series 차이 -> NaN 계산여부

In [ ]:
a1 = np.array([2, 2, 2, 2, np.NaN])
a1.mean() # nan 이 나온다...   numpy 의 경우 array 원소 중에 NaN 이 있으면 연산 불가 (즉 NaN 이 나옴)

nan

In [ ]:
pd.Series(a1)

0    2.0
1    2.0
2    2.0
3    2.0
4    NaN
dtype: float64

In [ ]:
pd.Series(a1).mean()   # NaN 을 배제하고 평균값을 계산해냅니다

2.0

In [ ]:
s1.mean()  # NaN 을 배제하고 평균값을 계산해냅니다

2.6666666666666665

In [ ]:
# 빈도수 계산
s1.value_counts()  # 결과 타입이 series 다!

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
dtype: int64

# head, tail 함수
 - head : 상위 n개 출력 기본 5개
 - tail : 하위 n개 출력 기본 5개

In [ ]:
s1.head()

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
dtype: float64

In [ ]:
s1.tail()

11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [ ]:
s1.head(3)

0    1.0
1    1.0
2    2.0
dtype: float64

# Series 의 연산

## index 기존으로 연산

In [ ]:
# numpy 와 마찬가지로
# Series 도 Series 끼리 연산 가능.
#  기억하실 포인트는 '같은 인덱스' 기준으로 연산한다는 겁니다
#  이 특징은 DataFrame 에서도 동일하게 적용됩니다.

In [ ]:
s1 = pd.Series([1, 2, 3, 4], ['a', 'b', 'c', 'd'])
s2 = pd.Series([6, 3, 2, 1], ['d', 'c', 'b', 'a'])  # 인덱스 순서 다르다

In [ ]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s2

d    6
c    3
b    2
a    1
dtype: int64

In [ ]:
s1 + s2

a     2
b     4
c     6
d    10
dtype: int64

# 산술연산
 - Series의 경우에도 **스칼라와의 연산** 각 원소별로 스칼라와의 연산이 적용
 - Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용
   - 이때, 인덱스의 pair가 맞지 않으면, 결과는 NaN

In [ ]:
s1 ** 2

a     1
b     4
c     9
d    16
dtype: int64

In [ ]:
s1 ** s2   # 동일 인덱스에 맞게 연산됨!

a       1
b       4
c      27
d    4096
dtype: int64

In [ ]:
s1['k'] = 7
s2['e'] = 9

In [ ]:
s1

a    1
b    2
c    3
d    4
k    7
dtype: int64

In [ ]:
s2

d    6
c    3
b    2
a    1
e    9
dtype: int64

In [ ]:
s1 + s2  # ↓ index 'e', 'k' 는 연산이 불가능 하기 때문에 NaN

a     2.0
b     4.0
c     6.0
d    10.0
e     NaN
k     NaN
dtype: float64

 # **Boolean selection**
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨
  - 다중조건의 경우, &(and), |(or)를 사용하여 연결 가능

In [ ]:
s = pd.Series(np.arange(10), np.arange(10) + 1)
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int64

In [ ]:
s > 5
# 비교 연산의 결과 value 비교 결과들이 담긴 Boolean Series 나옴

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [ ]:
s[s > 5]  # boolean series 를 index 에 넣으면 필터링 됨.

7     6
8     7
9     8
10    9
dtype: int64

In [ ]:
# 짝수만 골라내기
s[s % 2 == 0]

1    0
3    2
5    4
7    6
9    8
dtype: int64

In [ ]:
# 기본적으로 Series 에 어떤 연산을 수행하면  Series 의 index 가 아닌 value 에 대해 동작했다.

# 이제 index 에 대해 필터링을 해보겠습니다

In [ ]:
s.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [ ]:
s.index > 5  # 이 결과 또한 boolean series

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
s[s.index > 5]

6     5
7     6
8     7
9     8
10    9
dtype: int64

In [ ]:
(s > 5) & (s < 8)  # 주의 ! 괄호 안하면 에러다!

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
dtype: bool

In [ ]:
s[(s > 5) & (s < 8)]

7    6
8    7
dtype: int64

In [ ]:
# 7보다 같거나 큰 값들의 합은?
s[s >= 7].sum()

24

# Series 값 변경
- 추가 및 업데이트: 인덱스 사용
- 삭제: drop 함수 사용
- inplace=  파라미터

In [ ]:
s = pd.Series(np.arange(100, 105), ['a', 'b', 'c', 'd', 'e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [ ]:
# 값 변경
s['a'] = 200
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [ ]:
s['k'] = 300  # 생성(추가)
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [ ]:
# 삭제
s.drop('k')  # index k 가 삭제된 새로운 Series 생성하여 리턴 (원본 s 는 변화 없다)

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [ ]:
s  # 원본에는 여전히 k 남아있다

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [ ]:
# ★중요★
# drop() 함수는 drop 한'결과' 를 새로 만들어서 리턴한거고
# 원본 데이터 s 는 '변경'하지 않습니다

# numpy , pandas, 그밖의 수많은 데이터 관련 모듈들 에서의
# 대부분의 객체 함수들은 호출한 원본 객체를 '변경'하진 않고
# 원본의 '사본'을 만든뒤 '사본' 에 연산수행하여 그 '사본' 을 리턴하도록 동작 한다
# (함수마다 조금씩 다르긴 하다)

# 그러나!
# inplace=True 파라미터를 주면 '사본' 을 만들지 않고 '원본'을 변화시키도록 동작한다


In [ ]:
s.drop('k', inplace=True)  # 리턴값이 None!  (원본 변경됨!)

In [ ]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

# **Slicing**
 - 리스트, ndarray와 동일하게 적용
 - index 가 문자열인 경우 slicing 시 마지막도 포함 (ndarray 와 차이점!)

In [ ]:
s1 = pd.Series(np.arange(100, 105))
s1

0    100
1    101
2    102
3    103
4    104
dtype: int64

In [ ]:
s1[1:3]

1    101
2    102
dtype: int64

In [ ]:
# 인덱스가 '문자' 인경우는 어떻게 될까?
s2 = pd.Series(np.arange(100, 105), ['a','b','c','d','e'])
s2

a    100
b    101
c    102
d    103
e    104
dtype: int64

In [ ]:
s2['a']

100

In [ ]:
s2[1]  # 인덱스가 문자인 경우. 이게 된다!?

101

In [ ]:
s3[1:3]  # 작동한다!!

1    1
2    2
dtype: int64

In [ ]:
# 인덱스가 숫자타입이 아닌경우, 0-base 인덱싱, 슬라이싱 사용 가능


In [ ]:
# 인덱스 순서를 살짝 변경해보면
s2 =  pd.Series(np.arange(100, 105), ['a','c','b', 'd','e'])
s2

a    100
c    101
b    102
d    103
e    104
dtype: int64

In [ ]:
s2[1:3]

c    101
b    102
dtype: int64

In [ ]:
# 문자 타입 인덱스에 slicing 도 '문자' 로 가능할까?

In [ ]:
s2

a    100
c    101
b    102
d    103
e    104
dtype: int64

In [ ]:
s2['c':'d']  # 동작한다!
# 그러나!  문자열 슬라이싱의 경우 '마지막' 도 포함한다!

c    101
b    102
d    103
dtype: int64

In [ ]:
s2['b': 'c']

Series([], dtype: int64)

In [ ]:
s2['b': 'c': -1]

b    102
c    101
dtype: int64

# Multi level index

In [ ]:
s3 = pd.Series([1, 2, 3, 4, 5, 6], ['a', 'a', 'b', 'b', 'c', 'c'])
s3

a    1
a    2
b    3
b    4
c    5
c    6
dtype: int64

In [ ]:
s3.index

Index(['a', 'a', 'b', 'b', 'c', 'c'], dtype='object')

In [ ]:
# ↑ 단일 level index 다!

In [ ]:
# multi-level index 를 가진 Series

s4 = pd.Series(
    np.arange(100, 106),
    index = [
        ['a', 'a', 'b', 'b', 'c', 'c'],
        [1,    2,   1,   2,   1,   2],
     ],
)

s4


a  1    100
   2    101
b  1    102
   2    103
c  1    104
   2    105
dtype: int64

In [ ]:
s4.index  # index 가 tuple 이다!

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
s4['a', 1]   # tuple 인덱싱으로 value 접근!

100

In [ ]:
s4['a']
# s4 : 2-level index
# s4['a'] : 1-level index

1    100
2    101
dtype: int64

In [ ]:
s4['a'][1]

100

In [ ]:
s4['a':'b']  # 상위 level (level 0) 슬라이스 의 인덱스 사용

a  1    100
   2    101
b  1    102
   2    103
dtype: int64

In [ ]:
s4[['a', 'c']]

a  1    100
   2    101
c  1    104
   2    105
dtype: int64

#### xs() 를 사용한 인덱스
cross-section

axis = 0, level = 0

In [ ]:
s4.xs('a')   # <= s4['a'] 와 동일   (상위 level 인덱스)

1    100
2    101
dtype: int64

In [ ]:
s4.xs(('a', 1))  # <= s4['a', 1] 와 동일

100

In [ ]:
s4

a  1    100
   2    101
b  1    102
   2    103
c  1    104
   2    105
dtype: int64

In [ ]:
# s4.xs(2)   # 상위 level 의 인덱스에는 2 가 없다!

KeyError: 2

In [ ]:
s4.xs(2, level=1)

a    101
b    103
c    105
dtype: int64

In [ ]:
s4

a  1    100
   2    101
b  1    102
   2    103
c  1    104
   2    105
dtype: int64

In [ ]:
s4.xs(2, level=-1)

a    101
b    103
c    105
dtype: int64

In [ ]:
# level 여러개 지정 가능
s4.xs((2, 'b'), level=(1, 0))

b  2    103
dtype: int64

# Series 에서 level 별 계산

In [ ]:
data = pd.Series(
    [100, 200, 300, 400, 500, 600],
    index=[
        ["a", "a", "a", "b", "b", "c"],  # level 0 index
        [1,   2,   3,   1,   2,   1],    # level 1 index
    ]
)
data

a  1    100
   2    200
   3    300
b  1    400
   2    500
c  1    600
dtype: int64

In [ ]:
data.sum()

2100

In [ ]:
data.mean()

350.0

In [ ]:
data.sum(level = None)  # level=None : 디폴트.  전체 value  에 대한 연산

2100

In [ ]:
data.sum(level=0)  # level=0  인덱스가 같은 value 끼리 연산

<ipython-input-150-33b3b1db3189>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  data.sum(level=0)


a    600
b    900
c    600
dtype: int64

In [ ]:
data.groupby(level=1).sum()

1    1100
2     700
3     300
dtype: int64

In [ ]:
data.sum(level=1)

<ipython-input-153-35722a8e036e>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  data.sum(level=1)


1    1100
2     700
3     300
dtype: int64