<a href="https://colab.research.google.com/github/leejonghyeon99/python_stu/blob/main/02_ndarray%EC%9D%98_%EC%9D%B8%EB%8D%B1%EC%8B%B1%2C_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1%2C_shape_%EB%B3%80%EA%B2%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 인덱싱 index
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능
 - 인덱싱 할때마다 차원감소


In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[0]

0

In [5]:
x[-1], x[9]

(9, 9)

In [6]:
x[3] = 100

In [7]:
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [9]:
# x[100] # indexError : index 100 is out of bounds for axis 0 with size 10

In [11]:
x.shape

(10,)

In [12]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
x[0]

array([0, 1, 2, 3, 4])

In [19]:
x[0][2], x[0, 2]  # <-- 콤마로 인덱싱 가능

# ★ numpy 에선 후자의 방법을 추천!

(2, 2)

In [21]:
x[1, 4], x[1, -1], x[-1, -1]

(9, 9, 9)

In [23]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [24]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
x[0, 1]

array([3, 4, 5])

In [26]:
x[0, 1, 2]

5

## 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능
 - 슬라이싱은 차원 변화 없다




In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [38]:
x[1::3]

array([1, 4, 7])

In [39]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 2차원 배열의 슬라이싱

In [40]:
y = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
y


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [45]:
y[0]

[0, 1, 2, 3, 4]

In [46]:
y[0:1]

[[0, 1, 2, 3, 4]]

In [47]:
y[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [50]:
# [[1, 2, 3]
#  [6, 7, 8]]

# list는 차원 축 슬라이싱 불가

# array는 가능

In [53]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
x[0:1]

array([[0, 1, 2, 3, 4]])

In [60]:
x[:2, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [68]:
x[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [69]:
x[:1, :2]

array([[0, 1]])

In [71]:
x[0, :2]  #[:1, :2] 와는 결과가 다르다, axis 0 은 인덱싱 => 차원감소된 결과

array([0, 1])

In [74]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
x[:1]

array([[0, 1, 2, 3, 4]])

In [90]:
print(x[:1].shape)
print(x[:1, 2])

(1, 5)
[2]


In [80]:
# x[:1][2] # IndexError: index 2 is out of bounds for axis 0 with size 1

# iterable
ndarray 는 iterable 객체다

In [92]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [93]:
for item in arr:
  print(item)

1
2
3
4
5


In [99]:
# list(arr)

TypeError: 'list' object is not callable

In [97]:
arr.tolist()

[1, 2, 3, 4, 5]

# ndarray shape (차원) 변경하기
**차원변환**은 데이터분석 과 인공지능에서 매우 빈번하게 발생되는 작업이니만큼 자유자재로 변환할수 있어야 하고, 머리속으로 내가 변환하는 데이터의 구조가 그려지도록 익숙해져야 합니다

사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨




## ravel(), np.ravel()
  - [ˈrævl]
  - 다차원배열을 1차원으로 변경 (흔히 **'펼친다'**라고 말함)
  - 'order' 파라미터
    - 'C' - row 우선 변경 ,   C style
    - 'F - column 우선 변경,   Fortran style
  - ravel() 은 np 안에 일반 함수로도 있고, 혹은 ndarray 의 멤버함수로서도 존재




In [104]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [105]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [112]:
np.ravel(x, order='C') #axis 0 부터 펼쳐짐 (row 기준으로 펼쳐짐)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
np.ravel(x, order='F') #axis -1 부터 펼쳐짐 (column 기준으로 펼쳐짐)

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

## flatten()
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점:
     - copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
     - ndarray 의 멤버함수로만 제공됨
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경


In [116]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [119]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# ravel() vs. flatten() 차이점

In [120]:
temp = x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [121]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [123]:
temp[0] = 100
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [125]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [137]:
c = np.arange(10).reshape(2, 5)
a = c.flatten()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a[0] = 50
a, c

(array([50,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [141]:
temp2 = y.flatten()  # 데이터의 '복사본' 을 생성하는 flatten!
temp2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [142]:
temp2[0] = 100
temp2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [148]:
# y는 바뀌지 않는다 (원본 데이터 변화 x)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨
 - **-1** 값을 주어 나머지 차원을 유추하게 할수 있다


In [149]:
x2 = np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [150]:
x2.shape

(36,)

In [153]:
x2.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [156]:
x2.reshape(6, -1) # Asweom!
 # 앞의 차원이 정해지면 나머지는 유추할수 있다. 그게 -1 이다
                   # 정확한 값을 주지 않아도, 계산 귀찮으면 가능


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [157]:
x2.reshape(-1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [158]:
x2.reshape(6, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [160]:
# x2.reshape(6,-1,-1)  # 차원 유추 못해 파업

In [175]:
# 퀴즈

# 다음 주어진 array 에서 첫번째 col 만 추출하려면?

# array([[ 10,  20,  30,  40],
#        [  1,   2,   3,   4],
#        [100, 200, 300, 400]])

""" 결과
array([ 10,   1, 100])
"""

arr31 = np.array([[ 10,  20,  30,  40],
                  [  1,   2,   3,   4],
                  [100, 200, 300, 400]])
arr31

arr31[:, 0]

array([ 10,   1, 100])

## 차원 확장 / 제거

- 차원 확장/제거 하는 동작도 머신러닝에서 많이 사용된다.
- **reshape()** 로 차원 변환(확장/제거) 자유롭게 가능

## 차원 확장 : np.expand_dims()
- axis로 지정된 '차원을 추가'한다.


## 차원 자동 제거 : squeeze, np.squeeze()

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 '차원을 제거'한다.


In [180]:
x3 = np.arange(6)
x3

array([0, 1, 2, 3, 4, 5])

In [184]:
x3.shape, x3.ndim, x.size

((6,), 1, 15)

In [183]:
x3.reshape(6, 1) # 2차원으로 차원 확장환 결과

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [186]:
x3 = x3.reshape(6,1)
x3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [187]:
x3.shape, x3.ndim, x3.size

((6, 1), 2, 6)

In [192]:
x3 = x3.reshape(6, 1, 1) # 3차원으로 차원 확장
x3

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [191]:
x3.shape, x3.ndim, x3.size

((1, 6, 1), 3, 6)

In [199]:
x3 = x3.reshape((6,)) #다시 1차원으로 차원 축소 (차원제거)
x3

array([0, 1, 2, 3, 4, 5])

In [203]:
x3 = x3.reshape((1,6))
x3

array([[0, 1, 2, 3, 4, 5]])

In [204]:
x3.shape, x3.ndim

((1, 6), 2)

In [205]:
# squeeze() : 차원중 사이즈가 1인것을 찾아서 제거

In [206]:
x3.squeeze()

array([0, 1, 2, 3, 4, 5])

In [214]:
x4 = np.arange(8).reshape((2,1,4,1))
x4

array([[[[0],
         [1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6],
         [7]]]])

In [215]:
x4.squeeze()

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### np.expand_dims()

- expand_dims는 axis로 지정된 차원을 추가한다.
- axis 는 차원의 축
    - 2차원은 axis => 0, 1
    - 3차원은 axis => 0, 1, 2
    - ...
    
- axis 는 음수값 지원




In [217]:
x5 = np.arange(3)
x5

array([0, 1, 2])

In [218]:
x5.shape

(3,)

In [228]:
y5 = np.expand_dims(x5,0) # 0 번째 axis 에 새로운 차원 추가(삽입)
y5

array([[0, 1, 2]])

In [229]:
y5.shape  #  (3, ) => (1, 3)

(1, 3)

In [230]:
x6 = np.arange(4).reshape((2, 2))
x6

array([[0, 1],
       [2, 3]])

In [231]:
x6.shape

(2, 2)

In [232]:
# (2, 2) => (2, 1, 2)
z = np.expand_dims(x6,1)
z

array([[[0, 1]],

       [[2, 3]]])

In [233]:
z.shape

(2, 1, 2)

In [234]:
# 마지막에 차원 추가하기,   -1
칠 = np.expand_dims(x6, -1)
칠

array([[[0],
        [1]],

       [[2],
        [3]]])

### np.newaxis

In [238]:
소문자에이 = np.array([2, 0, 1, 8])
소문자에이

array([2, 0, 1, 8])

In [239]:
소문자에이.shape

(4,)

In [247]:
소문자에이1 = 소문자에이[np.newaxis, :]
소문자에이1

array([[2, 0, 1, 8]])

In [248]:
소문자에이1.shape

(1, 4)

In [ ]:
# 1차원 벡터를 row vector 로 변환한다라고 함

In [253]:
한글로변수명짓기일번 = 소문자에이[:, np.newaxis]  # (4, 1)
한글로변수명짓기일번

array([[2],
       [0],
       [1],
       [8]])

In [251]:
# 1차원 벡터를 column vector 로 변환한다라고 함

# transpose, T,  swapaxes
전치행렬 (transpose matrix) , 차원 축 바꾸기

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbtmNz3%2FbtqDk6Xy5nh%2FD7U80E2R3fnahK00cijoY1%2Fimg.png)


In [257]:
에이 = np.arange(15).reshape(3, 5)
에이, 에이.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 (3, 5))

In [258]:
np.transpose(에이), np.transpose(에이).shape

(array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 (5, 3))

In [259]:
에이.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [260]:
np.swapaxes(에이, 0, 1)  # axis 0 와 axis 1을 바꾸기

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])